---
new_page_extension: html
auto_deploy: true
admin_path: ylijumala
webhook_url: 
collections:
  _posts:
    default_front_matter_template: post
  _projects:
    default_front_matter_template: project
  _people:
    default_front_matter_template: person
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
